name=htcw_gfx
version=2.9.1
author=honey the codewitch
maintainer=honey the codewitch
sentence=Provides cross platform graphics
paragraph=Provides cross platform graphics functionality
category=Display
url=https://github.com/codewitch-honey-crisis/gfx
depends=htcw_data (>=1.4.6 && <1.5.0),htcw_ml (>=0.2.10 && <0.3.0)
architectures=*
 